### PR TITLE
Fix/attribution

### PR DESCRIPTION
**Pull request by seanebum**
This fixes the attribution issue caused by adding/removing layers.  Before this PR, when selecting a data layer, the basemap attributions were being overwritten/replaced by the layer attributions.  This PR combines attributions so that both basemap and additional layer attributions are displayed.

### CODE REVIEW

**Comment by seanebum** [comment]
At current state, all added layer attributions are added to the attributions section.  This is probably not desirable, and should be updated to only display layer attributions for either A) the current view port or B) the selected region.  selected region would likely be a lot easier!

**Comment by jeffbliss** [comment]
Do we want/need to show attributions at all? There's a way to turn it off entirely. Just curious.

**Comment by seanebum** [comment]
> Do we want/need to show attributions at all? There's a way to turn it off entirely. Just curious.

I'm not sure one way or the other - turning it off would be super easy.  Right now as far as I can tell, there's doesn't seem to be a way to directly pull the attributions out of the ESRI VectorBasemapLayer() object, so the attributions from any added layers have to be passed into the VectorBasemapLayer() (which means re-rendering the basemap - I haven't found a way to update + refresh the attributions otherwise yet... this is super annoying)

**Comment by daveism** [comment]
> > Do we want/need to show attributions at all? There's a way to turn it off entirely. Just curious.
> 
> I'm not sure one way or the other - turning it off would be super easy. Right now as far as I can tell, there's doesn't seem to be a way to directly pull the attributions out of the ESRI VectorBasemapLayer() object, so the attributions from any added layers have to be passed into the VectorBasemapLayer() (which means re-rendering the basemap - I haven't found a way to update + refresh the attributions otherwise yet... this is super annoying)

let's update when we select a region and we to have to include the attributes what the ESRI basemaps.

**Pull request merged**
