### PR TITLE
Identify

### PR DESCRIPTION
**Pull request by jeffbliss**
This PR brings in the identify functionality.

### CODE REVIEW

**Review by daveism — CHANGES_REQUESTED** [review]
Please fix the lint issues from `run lint-test `

**Review by daveism — CHANGES_REQUESTED** [review]
Nevermind I missed that I needed to do an npm install

**Comment by jeffbliss** [comment]
All lint errors are fixed and I rewrote identify like we discussed yesterday.

**Review by seanebum — APPROVED** [review]

**Review by jeffbliss — COMMENTED** [review]
Made changes

**Review by daveism — APPROVED** [review]
Two things are not code related

1. tab switching removes the popup ( as mentioned )
2. Clicking on the map removes the popup

I am fine with merging but we will have to resolve both at some point just wanted to document the issues

**Pull request merged**
